// Generated by gencpp from file beginner_tutorials/DataToAssociate.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_DATATOASSOCIATE_H
#define BEGINNER_TUTORIALS_MESSAGE_DATATOASSOCIATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <beginner_tutorials/Point2D.h>
#include <std_msgs/Float32MultiArray.h>
#include <beginner_tutorials/Point2D.h>

namespace beginner_tutorials
{
template <class ContainerAllocator>
struct DataToAssociate_
{
  typedef DataToAssociate_<ContainerAllocator> Type;

  DataToAssociate_()
    : features()
    , featureCovMatrices()
    , measurements()  {
    }
  DataToAssociate_(const ContainerAllocator& _alloc)
    : features(_alloc)
    , featureCovMatrices(_alloc)
    , measurements(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::beginner_tutorials::Point2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::beginner_tutorials::Point2D_<ContainerAllocator> >::other >  _features_type;
  _features_type features;

   typedef std::vector< ::std_msgs::Float32MultiArray_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::std_msgs::Float32MultiArray_<ContainerAllocator> >::other >  _featureCovMatrices_type;
  _featureCovMatrices_type featureCovMatrices;

   typedef std::vector< ::beginner_tutorials::Point2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::beginner_tutorials::Point2D_<ContainerAllocator> >::other >  _measurements_type;
  _measurements_type measurements;




  typedef boost::shared_ptr< ::beginner_tutorials::DataToAssociate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::DataToAssociate_<ContainerAllocator> const> ConstPtr;

}; // struct DataToAssociate_

typedef ::beginner_tutorials::DataToAssociate_<std::allocator<void> > DataToAssociate;

typedef boost::shared_ptr< ::beginner_tutorials::DataToAssociate > DataToAssociatePtr;
typedef boost::shared_ptr< ::beginner_tutorials::DataToAssociate const> DataToAssociateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::DataToAssociate_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::DataToAssociate_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials': ['/home/daniel/catkin_ws/src/beginner_tutorials/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::DataToAssociate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::DataToAssociate_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::DataToAssociate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::DataToAssociate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::DataToAssociate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::DataToAssociate_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::DataToAssociate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "741a60cbfa41b774cb163e0c6d768d77";
  }

  static const char* value(const ::beginner_tutorials::DataToAssociate_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x741a60cbfa41b774ULL;
  static const uint64_t static_value2 = 0xcb163e0c6d768d77ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::DataToAssociate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/DataToAssociate";
  }

  static const char* value(const ::beginner_tutorials::DataToAssociate_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::DataToAssociate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Point2D[] features\n\
std_msgs/Float32MultiArray[] featureCovMatrices\n\
Point2D[] measurements\n\
================================================================================\n\
MSG: beginner_tutorials/Point2D\n\
float64 x\n\
float64 y\n\
================================================================================\n\
MSG: std_msgs/Float32MultiArray\n\
# Please look at the MultiArrayLayout message definition for\n\
# documentation on all multiarrays.\n\
\n\
MultiArrayLayout  layout        # specification of data layout\n\
float32[]         data          # array of data\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/MultiArrayLayout\n\
# The multiarray declares a generic multi-dimensional array of a\n\
# particular data type.  Dimensions are ordered from outer most\n\
# to inner most.\n\
\n\
MultiArrayDimension[] dim # Array of dimension properties\n\
uint32 data_offset        # padding elements at front of data\n\
\n\
# Accessors should ALWAYS be written in terms of dimension stride\n\
# and specified outer-most dimension first.\n\
# \n\
# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n\
#\n\
# A standard, 3-channel 640x480 image with interleaved color channels\n\
# would be specified as:\n\
#\n\
# dim[0].label  = \"height\"\n\
# dim[0].size   = 480\n\
# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n\
# dim[1].label  = \"width\"\n\
# dim[1].size   = 640\n\
# dim[1].stride = 3*640 = 1920\n\
# dim[2].label  = \"channel\"\n\
# dim[2].size   = 3\n\
# dim[2].stride = 3\n\
#\n\
# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n\
\n\
================================================================================\n\
MSG: std_msgs/MultiArrayDimension\n\
string label   # label of given dimension\n\
uint32 size    # size of given dimension (in type units)\n\
uint32 stride  # stride of given dimension\n\
";
  }

  static const char* value(const ::beginner_tutorials::DataToAssociate_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::DataToAssociate_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.features);
      stream.next(m.featureCovMatrices);
      stream.next(m.measurements);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DataToAssociate_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::DataToAssociate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::DataToAssociate_<ContainerAllocator>& v)
  {
    s << indent << "features[]" << std::endl;
    for (size_t i = 0; i < v.features.size(); ++i)
    {
      s << indent << "  features[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::beginner_tutorials::Point2D_<ContainerAllocator> >::stream(s, indent + "    ", v.features[i]);
    }
    s << indent << "featureCovMatrices[]" << std::endl;
    for (size_t i = 0; i < v.featureCovMatrices.size(); ++i)
    {
      s << indent << "  featureCovMatrices[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::std_msgs::Float32MultiArray_<ContainerAllocator> >::stream(s, indent + "    ", v.featureCovMatrices[i]);
    }
    s << indent << "measurements[]" << std::endl;
    for (size_t i = 0; i < v.measurements.size(); ++i)
    {
      s << indent << "  measurements[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::beginner_tutorials::Point2D_<ContainerAllocator> >::stream(s, indent + "    ", v.measurements[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_DATATOASSOCIATE_H
